imports:
    - { resource: services.yml }

oneup_uploader:
    mappings:
        gallery:
            frontend: dropzone
    chunks:
        maxage: 86400
        storage:
            directory: "%kernel.cache_dir%/uploader/chunks"